* dockerfile-mode
#+begin_src emacs-lisp :results silent
  (use-package dockerfile-mode
    :config
    (require 'dockerfile-mode)
    (add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode)))
#+end_src
